#!/bin/bash
set -x

mkdir -p deps
pushd deps
  installdir=`pwd`/install

  lwgrp_version=1.0.4
  lwgrp=lwgrp-${lwgrp_version}

  if [ ! -f ${lwgrp}.tar.gz ] ; then
    wget https://github.com/hpc/lwgrp/releases/download/v${lwgrp_version}/${lwgrp}.tar.gz
  fi

  rm -rf $installdir

  rm -rf ${lwgrp}
  tar -zxf ${lwgrp}.tar.gz
  pushd ${lwgrp}
    export CFLAGS=${OPT}
    ./configure \
      --prefix=${installdir} \
      --disable-silent-rules && \
    make && \
    make install
    if [ $? -ne 0 ]; then
      echo "failed to configure, build, or install liblwgrp"
      exit 1
    fi
  popd
popd

./autogen.sh

./configure --with-lwgrp=$installdir

make clean

make distcheck DISTCHECK_CONFIGURE_FLAGS="--with-lwgrp=$installdir"
